import json
from pathlib import Path

# Target directory
instructions_dir = Path("instructions")
instructions_dir.mkdir(parents=True, exist_ok=True)

def save_instructions(domain, data):
    file_path = instructions_dir / f"{domain}.json"
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    print(f"Wrote instructions: {domain}.json ({len(data)} items)")

# ── 1. Email Instructions ──
email_instructions = [
    # Type 1: Single
    {"id": "email_t1_001", "text": "Send an email to Alice at alice@example.com about the Q3 review status.", "type": 1, "difficulty": "easy", "domain": "email", "expected_tools": ["send_email"], "notes": "Simple send email request"},
    {"id": "email_t1_002", "text": "Check my inbox for emails from John regarding the budget.", "type": 1, "difficulty": "easy", "domain": "email", "expected_tools": ["search_inbox"], "notes": "Search inbox for specific sender and keyword"},
    {"id": "email_t1_003", "text": "Mark the email thread with id thread_9988 as read.", "type": 1, "difficulty": "easy", "domain": "email", "expected_tools": ["mark_read"], "notes": "Mark read by thread/message ID"},
    {"id": "email_t1_004", "text": "Retrieve the full message history of thread th_12345.", "type": 1, "difficulty": "easy", "domain": "email", "expected_tools": ["get_thread"], "notes": "Fetch thread by ID"},
    {"id": "email_t1_005", "text": "Email boss@company.com and cc hr@company.com with the subject 'Vacation Request' and body 'Please approve my time off.'", "type": 1, "difficulty": "easy", "domain": "email", "expected_tools": ["send_email"], "notes": "Email with CC"},
    {"id": "email_t1_006", "text": "Search for any unread draft emails in my folder.", "type": 1, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox"], "notes": "Search drafts folder with unread filter"},
    {"id": "email_t1_007", "text": "Mark these messages as starred: msg_1, msg_2, msg_3.", "type": 1, "difficulty": "easy", "domain": "email", "expected_tools": ["mark_read"], "notes": "Batch update status to starred"},
    {"id": "email_t1_008", "text": "Get the email thread th_abc123 and order messages with the newest first.", "type": 1, "difficulty": "medium", "domain": "email", "expected_tools": ["get_thread"], "notes": "Thread retrieval with desc order"},
    {"id": "email_t1_009", "text": "Find all emails with attachments received between March 1st and April 1st, 2024.", "type": 1, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox"], "notes": "Search with date filters and has_attachment flag"},
    {"id": "email_t1_010", "text": "Reply to boss@company.com about the schedule, reply-to routing to dev@company.com.", "type": 1, "difficulty": "medium", "domain": "email", "expected_tools": ["send_email"], "notes": "Email with reply_to override"},
    {"id": "email_t1_011", "text": "Search inbox folder for emails containing 'urgent' with limit of 50 results.", "type": 1, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox"], "notes": "Search with limits"},
    {"id": "email_t1_012", "text": "Schedule an email to team@company.com for tomorrow morning at 9:00 AM.", "type": 1, "difficulty": "hard", "domain": "email", "expected_tools": ["send_email"], "notes": "Email with scheduled send timestamp"},
    {"id": "email_t1_013", "text": "Mark thread msg_x99 as read and move to archive folder.", "type": 1, "difficulty": "medium", "domain": "email", "expected_tools": ["mark_read"], "notes": "Mark read with folder parameter"},

    # Type 2: Chain
    {"id": "email_t2_001", "text": "Find the last email from Bob, then retrieve the full conversation thread for it.", "type": 2, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox", "get_thread"], "notes": "Search Bob's email, extract thread_id, then get thread"},
    {"id": "email_t2_002", "text": "Search for emails containing 'invoice', mark them all as important, then get the thread details of the first one.", "type": 2, "difficulty": "hard", "domain": "email", "expected_tools": ["search_inbox", "mark_read", "get_thread"], "notes": "Search invoice, get message IDs, mark read/important, then get thread"},
    {"id": "email_t2_003", "text": "Check if there are any unread emails from hr@company.com, if so, retrieve the thread history and then send a reply.", "type": 2, "difficulty": "hard", "domain": "email", "expected_tools": ["search_inbox", "get_thread", "send_email"], "notes": "Find unread, fetch thread, send response"},
    {"id": "email_t2_004", "text": "Search inbox for 'status update', get the message thread, then mark all messages in that thread as read.", "type": 2, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox", "get_thread", "mark_read"], "notes": "Search, fetch thread, extract message IDs, mark read"},
    {"id": "email_t2_005", "text": "Find the email from boss@company.com about Q3 goals, get its thread, and check if it has attachments.", "type": 2, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox", "get_thread"], "notes": "Search sender, get thread, inspect structure"},
    {"id": "email_t2_006", "text": "Search drafts for 'newsletter', open the thread, then send the email to subscribe@news.com.", "type": 2, "difficulty": "hard", "domain": "email", "expected_tools": ["search_inbox", "get_thread", "send_email"], "notes": "Search drafts, load thread, send email with draft body"},
    {"id": "email_t2_007", "text": "Check my sent folder for the email to client@partner.com, and if found, mark it as starred.", "type": 2, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox", "mark_read"], "notes": "Search sent, mark starred"},
    {"id": "email_t2_008", "text": "Look up emails from security@company.com, get the newest thread, and verify the sender address.", "type": 2, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox", "get_thread"], "notes": "Search, get thread"},
    {"id": "email_t2_009", "text": "Find billing emails, mark them as read, and then reply to billing@company.com.", "type": 2, "difficulty": "hard", "domain": "email", "expected_tools": ["search_inbox", "mark_read", "send_email"], "notes": "Search, mark read, send email"},
    {"id": "email_t2_010", "text": "Search for drafts with the subject 'Project Alpha', get the thread, then schedule it to send later.", "type": 2, "difficulty": "hard", "domain": "email", "expected_tools": ["search_inbox", "get_thread", "send_email"], "notes": "Search drafts, get thread, send with schedule_send"},
    {"id": "email_t2_011", "text": "Find the message ID of the email about 'system down', then mark it as important.", "type": 2, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox", "mark_read"], "notes": "Search, mark important"},
    {"id": "email_t2_012", "text": "Get thread th_4455, parse the messages, and send a forward email to archive@company.com.", "type": 2, "difficulty": "medium", "domain": "email", "expected_tools": ["get_thread", "send_email"], "notes": "Get thread, send forward"},

    # Type 3: Ambiguous
    {"id": "email_t3_001", "text": "Send an email.", "type": 3, "difficulty": "easy", "domain": "email", "expected_tools": [], "notes": "Missing 'to', 'subject', and 'body' parameters. Must ask for clarification."},
    {"id": "email_t3_002", "text": "Search my emails.", "type": 3, "difficulty": "easy", "domain": "email", "expected_tools": [], "notes": "Missing 'query' parameter."},
    {"id": "email_t3_003", "text": "Mark my emails as read.", "type": 3, "difficulty": "medium", "domain": "email", "expected_tools": [], "notes": "Missing 'message_ids' parameter. Needs clarification on which emails."},
    {"id": "email_t3_004", "text": "Get the email thread.", "type": 3, "difficulty": "easy", "domain": "email", "expected_tools": [], "notes": "Missing 'thread_id' parameter."},
    {"id": "email_t3_005", "text": "Email John.", "type": 3, "difficulty": "easy", "domain": "email", "expected_tools": [], "notes": "Missing email address, subject, and body."},
    {"id": "email_t3_006", "text": "Check if I got the contract in my email.", "type": 3, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox"], "notes": "Ambiguous search query, needs to search for 'contract' in inbox folder."},
    {"id": "email_t3_007", "text": "Send a markdown email to boss@company.com.", "type": 3, "difficulty": "medium", "domain": "email", "expected_tools": [], "notes": "Missing subject and body."},
    {"id": "email_t3_008", "text": "Clear out my spam folder.", "type": 3, "difficulty": "hard", "domain": "email", "expected_tools": [], "notes": "Ambiguous action. Requires search_inbox then delete, but delete tool is in database domain, or we need to mark them. Clarification needed."},
    {"id": "email_t3_009", "text": "Find the attachments from yesterday.", "type": 3, "difficulty": "medium", "domain": "email", "expected_tools": [], "notes": "Missing query criteria. Needs to define 'yesterday' date filter and file type."},
    {"id": "email_t3_010", "text": "Mark all those messages as starred.", "type": 3, "difficulty": "medium", "domain": "email", "expected_tools": [], "notes": "Missing message_ids. Clarify which messages."},
    {"id": "email_t3_011", "text": "Check sent folder.", "type": 3, "difficulty": "easy", "domain": "email", "expected_tools": [], "notes": "Missing query filter. Search for what?"},
    {"id": "email_t3_012", "text": "Send the invoice report.", "type": 3, "difficulty": "medium", "domain": "email", "expected_tools": [], "notes": "Missing recipient email address."},
    {"id": "email_t3_013", "text": "Forward the meeting thread.", "type": 3, "difficulty": "medium", "domain": "email", "expected_tools": [], "notes": "Missing thread_id and recipient address."},

    # Type 4: Parallel
    {"id": "email_t4_001", "text": "Send emails to Alice (alice@example.com) and Bob (bob@example.com) about the project schedule separately.", "type": 4, "difficulty": "medium", "domain": "email", "expected_tools": ["send_email", "send_email"], "notes": "Two parallel send_email calls with different recipients"},
    {"id": "email_t4_002", "text": "Search for emails containing 'payment' and emails containing 'refund' in my inbox at the same time.", "type": 4, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox", "search_inbox"], "notes": "Two separate search_inbox queries in parallel"},
    {"id": "email_t4_003", "text": "Mark message msg_1 as starred and message msg_2 as read in parallel.", "type": 4, "difficulty": "medium", "domain": "email", "expected_tools": ["mark_read", "mark_read"], "notes": "Two parallel mark_read calls with different statuses"},
    {"id": "email_t4_004", "text": "Get thread th_1 and thread th_2 details simultaneously.", "type": 4, "difficulty": "easy", "domain": "email", "expected_tools": ["get_thread", "get_thread"], "notes": "Parallel get_thread calls"},
    {"id": "email_t4_005", "text": "Email ceo@company.com the audit report, and search my inbox for client emails at the same time.", "type": 4, "difficulty": "hard", "domain": "email", "expected_tools": ["send_email", "search_inbox"], "notes": "Send email and search inbox in parallel"},
    {"id": "email_t4_006", "text": "Mark message msg_101 as unread and get thread th_abc.", "type": 4, "difficulty": "medium", "domain": "email", "expected_tools": ["mark_read", "get_thread"], "notes": "Mark read and get thread in parallel"},
    {"id": "email_t4_007", "text": "Check inbox for security alerts and send a notification email to sysadmin@company.com.", "type": 4, "difficulty": "hard", "domain": "email", "expected_tools": ["search_inbox", "send_email"], "notes": "Search inbox and send email in parallel"},
    {"id": "email_t4_008", "text": "Send welcome emails to user1@domain.com, user2@domain.com, and user3@domain.com.", "type": 4, "difficulty": "hard", "domain": "email", "expected_tools": ["send_email", "send_email", "send_email"], "notes": "Three parallel send_email calls"},
    {"id": "email_t4_009", "text": "Find billing drafts and check thread th_invoice in parallel.", "type": 4, "difficulty": "medium", "domain": "email", "expected_tools": ["search_inbox", "get_thread"], "notes": "Search drafts and fetch thread"},
    {"id": "email_t4_010", "text": "Mark msg_a as read, msg_b as important, and msg_c as starred.", "type": 4, "difficulty": "hard", "domain": "email", "expected_tools": ["mark_read", "mark_read", "mark_read"], "notes": "Three parallel mark_read calls with different flags"},
    {"id": "email_t4_011", "text": "Fetch thread th_1 and send email to admin@company.com.", "type": 4, "difficulty": "medium", "domain": "email", "expected_tools": ["get_thread", "send_email"], "notes": "Get thread and send email in parallel"},
    {"id": "email_t4_012", "text": "Search for billing alerts and mark previous thread as read.", "type": 4, "difficulty": "hard", "domain": "email", "expected_tools": ["search_inbox", "mark_read"], "notes": "Search inbox and mark thread read in parallel"}
]
save_instructions("email", email_instructions)

# ── 2. Files Instructions ──
files_instructions = [
    # Type 1: Single
    {"id": "files_t1_001", "text": "Read the contents of path 'data/report.csv'.", "type": 1, "difficulty": "easy", "domain": "files", "expected_tools": ["read_file"], "notes": "Simple file read"},
    {"id": "files_t1_002", "text": "Write the text 'Hello Sandbox' to output/log.txt in append mode.", "type": 1, "difficulty": "easy", "domain": "files", "expected_tools": ["write_file"], "notes": "Write file with mode append"},
    {"id": "files_t1_003", "text": "List all json files in schemas/ directory.", "type": 1, "difficulty": "easy", "domain": "files", "expected_tools": ["list_directory"], "notes": "List directory with glob pattern"},
    {"id": "files_t1_004", "text": "Move file temp/data.csv to data/archive.csv.", "type": 1, "difficulty": "easy", "domain": "files", "expected_tools": ["move_file"], "notes": "Simple move file"},
    {"id": "files_t1_005", "text": "Read the first 50 lines of configuration file config/settings.json using utf-8 encoding.", "type": 1, "difficulty": "medium", "domain": "files", "expected_tools": ["read_file"], "notes": "Read file with start_line, end_line, and encoding"},
    {"id": "files_t1_006", "text": "Write base64 content aGVsbG8= to bin/asset.bin in overwrite mode.", "type": 1, "difficulty": "medium", "domain": "files", "expected_tools": ["write_file"], "notes": "Write file with base64 content"},
    {"id": "files_t1_007", "text": "Recursively list all files in project root directory.", "type": 1, "difficulty": "medium", "domain": "files", "expected_tools": ["list_directory"], "notes": "List directory with recursive flag"},
    {"id": "files_t1_008", "text": "Rename document notes.md to archive/old_notes.md, ensuring parent directories are created.", "type": 1, "difficulty": "medium", "domain": "files", "expected_tools": ["move_file"], "notes": "Move file creating directories"},
    {"id": "files_t1_009", "text": "Read the base64 formatted content of binary image files/photo.jpg.", "type": 1, "difficulty": "medium", "domain": "files", "expected_tools": ["read_file"], "notes": "Read binary format base64"},
    {"id": "files_t1_010", "text": "Write 'Status: Success' to system.log and backup the existing file.", "type": 1, "difficulty": "medium", "domain": "files", "expected_tools": ["write_file"], "notes": "Write with backup_existing"},
    {"id": "files_t1_011", "text": "List contents of folder data/ with a limit of 10 results, sorted by size.", "type": 1, "difficulty": "medium", "domain": "files", "expected_tools": ["list_directory"], "notes": "List directory with sorting and limit"},
    {"id": "files_t1_012", "text": "Read lines 100 to 200 of source code file main.py.", "type": 1, "difficulty": "easy", "domain": "files", "expected_tools": ["read_file"], "notes": "Read line range"},
    {"id": "files_t1_013", "text": "Move project folder src/ to build/src/ overwriting existing files.", "type": 1, "difficulty": "medium", "domain": "files", "expected_tools": ["move_file"], "notes": "Move folder with overwrite flag"},

    # Type 2: Chain
    {"id": "files_t2_001", "text": "List files in the download folder, then read the first csv file you find.", "type": 2, "difficulty": "medium", "domain": "files", "expected_tools": ["list_directory", "read_file"], "notes": "List folder, identify target path, then read file"},
    {"id": "files_t2_002", "text": "Read config/app.json, then write a modified backup version to config/app_backup.json in overwrite mode.", "type": 2, "difficulty": "medium", "domain": "files", "expected_tools": ["read_file", "write_file"], "notes": "Read config, write output"},
    {"id": "files_t2_003", "text": "Find all log files in logs/, move the oldest log file to archive/, then read its content to verify it.", "type": 2, "difficulty": "hard", "domain": "files", "expected_tools": ["list_directory", "move_file", "read_file"], "notes": "List logs, move target, read target"},
    {"id": "files_t2_004", "text": "Read output.txt, append new info to it, and move it to data/archive.txt.", "type": 2, "difficulty": "hard", "domain": "files", "expected_tools": ["read_file", "write_file", "move_file"], "notes": "Read, append (write), move"},
    {"id": "files_t2_005", "text": "List files in reports/ matching '*.csv', and if report_q1.csv is there, read it.", "type": 2, "difficulty": "medium", "domain": "files", "expected_tools": ["list_directory", "read_file"], "notes": "List, conditional read"},
    {"id": "files_t2_006", "text": "Read data/source.txt, base64 encode it, then write the base64 content to output/encoded.txt.", "type": 2, "difficulty": "hard", "domain": "files", "expected_tools": ["read_file", "write_file"], "notes": "Read raw, write base64"},
    {"id": "files_t2_007", "text": "Check if config.json exists by listing directory, and write 'verified' to status.log.", "type": 2, "difficulty": "medium", "domain": "files", "expected_tools": ["list_directory", "write_file"], "notes": "List check, write status"},
    {"id": "files_t2_008", "text": "Move old_data.csv to staging/data.csv, and read its first 10 lines to verify migration.", "type": 2, "difficulty": "medium", "domain": "files", "expected_tools": ["move_file", "read_file"], "notes": "Move then read first lines"},
    {"id": "files_t2_009", "text": "List directories recursively in backup/, find the latest sql script, and read its SQL content.", "type": 2, "difficulty": "hard", "domain": "files", "expected_tools": ["list_directory", "read_file"], "notes": "List recursive, read file"},
    {"id": "files_t2_010", "text": "Read lines 1 to 50 of user_data.csv, parse them, write them as user_subset.json, and list the output directory.", "type": 2, "difficulty": "hard", "domain": "files", "expected_tools": ["read_file", "write_file", "list_directory"], "notes": "Read subset, write new file, list check"},
    {"id": "files_t2_011", "text": "Find text files in notes/, rename text.txt to notes.txt, and write a confirmation note to confirm.log.", "type": 2, "difficulty": "hard", "domain": "files", "expected_tools": ["list_directory", "move_file", "write_file"], "notes": "List, move, write confirmation"},
    {"id": "files_t2_012", "text": "Read the contents of error.log, then clear it by writing an empty string in overwrite mode.", "type": 2, "difficulty": "medium", "domain": "files", "expected_tools": ["read_file", "write_file"], "notes": "Read then overwrite with empty content"},

    # Type 3: Ambiguous
    {"id": "files_t3_001", "text": "Read the file.", "type": 3, "difficulty": "easy", "domain": "files", "expected_tools": [], "notes": "Missing 'path' parameter. Must ask for clarification."},
    {"id": "files_t3_002", "text": "Write text to the log.", "type": 3, "difficulty": "easy", "domain": "files", "expected_tools": [], "notes": "Missing 'content' and 'mode' parameters, and path is vague."},
    {"id": "files_t3_003", "text": "List my folder.", "type": 3, "difficulty": "easy", "domain": "files", "expected_tools": [], "notes": "Missing 'path' parameter."},
    {"id": "files_t3_004", "text": "Move the file to archive.", "type": 3, "difficulty": "easy", "domain": "files", "expected_tools": [], "notes": "Missing 'source_path' and exact 'destination_path'."},
    {"id": "files_t3_005", "text": "Open file data.txt.", "type": 3, "difficulty": "medium", "domain": "files", "expected_tools": ["read_file"], "notes": "Vague command 'open'. Maps to read_file, but missing optional limits, uses default utf-8."},
    {"id": "files_t3_006", "text": "Save data to project.json.", "type": 3, "difficulty": "medium", "domain": "files", "expected_tools": [], "notes": "Missing 'content' data and write 'mode' parameter."},
    {"id": "files_t3_007", "text": "Show me files.", "type": 3, "difficulty": "easy", "domain": "files", "expected_tools": [], "notes": "Missing 'path' parameter."},
    {"id": "files_t3_008", "text": "Backup my file.", "type": 3, "difficulty": "medium", "domain": "files", "expected_tools": [], "notes": "Missing source path and target destination path."},
    {"id": "files_t3_009", "text": "Read config setting.", "type": 3, "difficulty": "medium", "domain": "files", "expected_tools": [], "notes": "Vague query, which file in config? Missing path."},
    {"id": "files_t3_010", "text": "Append this text.", "type": 3, "difficulty": "easy", "domain": "files", "expected_tools": [], "notes": "Missing file path to write to."},
    {"id": "files_t3_011", "text": "Move main.py.", "type": 3, "difficulty": "easy", "domain": "files", "expected_tools": [], "notes": "Missing destination path."},
    {"id": "files_t3_012", "text": "Read user file using base64 encoding.", "type": 3, "difficulty": "medium", "domain": "files", "expected_tools": [], "notes": "Missing file path parameter."},
    {"id": "files_t3_013", "text": "Clean my temp directory.", "type": 3, "difficulty": "hard", "domain": "files", "expected_tools": [], "notes": "Ambiguous instruction. Requires listing files then moving or deleting them. Clarification needed."},

    # Type 4: Parallel
    {"id": "files_t4_001", "text": "Read 'data/report1.csv' and 'data/report2.csv' at the same time.", "type": 4, "difficulty": "easy", "domain": "files", "expected_tools": ["read_file", "read_file"], "notes": "Two parallel read_file calls"},
    {"id": "files_t4_002", "text": "Write logs to 'output/err.log' and write stats to 'output/metrics.json' in parallel.", "type": 4, "difficulty": "medium", "domain": "files", "expected_tools": ["write_file", "write_file"], "notes": "Two parallel write_file calls"},
    {"id": "files_t4_003", "text": "List files in 'src/' and list files in 'tests/' simultaneously.", "type": 4, "difficulty": "easy", "domain": "files", "expected_tools": ["list_directory", "list_directory"], "notes": "Parallel list_directory calls"},
    {"id": "files_t4_004", "text": "Move 'file1.txt' to 'archive/1.txt' and 'file2.txt' to 'archive/2.txt' together.", "type": 4, "difficulty": "medium", "domain": "files", "expected_tools": ["move_file", "move_file"], "notes": "Parallel move_file calls"},
    {"id": "files_t4_005", "text": "Read 'config.json' while listing 'exports/' directory.", "type": 4, "difficulty": "medium", "domain": "files", "expected_tools": ["read_file", "list_directory"], "notes": "Read file and list directory in parallel"},
    {"id": "files_t4_006", "text": "Write results to 'results.txt' and move the draft file 'draft.csv' to 'data/' in parallel.", "type": 4, "difficulty": "hard", "domain": "files", "expected_tools": ["write_file", "move_file"], "notes": "Write file and move file in parallel"},
    {"id": "files_t4_007", "text": "Read 'system.log', write backup to 'backup.log', and list 'logs/' directory in parallel.", "type": 4, "difficulty": "hard", "domain": "files", "expected_tools": ["read_file", "write_file", "list_directory"], "notes": "Three parallel file tool calls"},
    {"id": "files_t4_008", "text": "Move three script files: 'a.py', 'b.py', 'c.py' to 'scripts/' folder simultaneously.", "type": 4, "difficulty": "hard", "domain": "files", "expected_tools": ["move_file", "move_file", "move_file"], "notes": "Three parallel move_file calls"},
    {"id": "files_t4_009", "text": "Read the header of 'data.csv' and write the timestamp to 'time.txt' in parallel.", "type": 4, "difficulty": "medium", "domain": "files", "expected_tools": ["read_file", "write_file"], "notes": "Read line range and write text in parallel"},
    {"id": "files_t4_010", "text": "List 'data/' folder and list 'reports/' folder in parallel.", "type": 4, "difficulty": "easy", "domain": "files", "expected_tools": ["list_directory", "list_directory"], "notes": "Parallel list directory"},
    {"id": "files_t4_011", "text": "Write 'active' to status.log and read settings.json at the same time.", "type": 4, "difficulty": "medium", "domain": "files", "expected_tools": ["write_file", "read_file"], "notes": "Write and read in parallel"},
    {"id": "files_t4_012", "text": "Move 'app.log' to 'archive/' and list files in 'archive/' simultaneously.", "type": 4, "difficulty": "hard", "domain": "files", "expected_tools": ["move_file", "list_directory"], "notes": "Move file and list directory in parallel"}
]
save_instructions("files", files_instructions)

# ── 3. Notifications Instructions ──
notifications_instructions = [
    # Type 1: Single
    {"id": "notifications_t1_001", "text": "Send a push notification to user_101 with title 'Alert' and body 'Low storage'.", "type": 1, "difficulty": "easy", "domain": "notifications", "expected_tools": ["send_push"], "notes": "Simple send push notification"},
    {"id": "notifications_t1_002", "text": "Send an SMS message 'Your verification code is 1234' to +12125550199.", "type": 1, "difficulty": "easy", "domain": "notifications", "expected_tools": ["send_sms"], "notes": "Send SMS with E.164 phone number"},
    {"id": "notifications_t1_003", "text": "Post 'Build passed successfully' to Slack channel #deployments.", "type": 1, "difficulty": "easy", "domain": "notifications", "expected_tools": ["send_slack_message"], "notes": "Send Slack channel message"},
    {"id": "notifications_t1_004", "text": "Send high-priority push notification to user_998: 'Urgent security breach!' with click action 'settings'.", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_push"], "notes": "Push notification with custom priority and click action"},
    {"id": "notifications_t1_005", "text": "Schedule SMS 'Happy Birthday!' to +447911123456 for sending tomorrow at 12:00 PM UTC.", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_sms"], "notes": "Scheduled SMS with timestamp"},
    {"id": "notifications_t1_006", "text": "Post message to channel C12345: 'Incident report' using Slack Block Kit blocks.", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_slack_message"], "notes": "Slack message with blocks payload"},
    {"id": "notifications_t1_007", "text": "Send push notification with metadata payload {'order_id': '456'} to customer dev_01.", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_push"], "notes": "Push notification with data dictionary"},
    {"id": "notifications_t1_008", "text": "Send a SMS message to +4930123456789 from phone number +18885550100.", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_sms"], "notes": "SMS specifying from_number"},
    {"id": "notifications_t1_009", "text": "Post thread reply to channel #bugs with parent timestamp 1712345678.0001.", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_slack_message"], "notes": "Slack message in thread"},
    {"id": "notifications_t1_010", "text": "Send SMS with emoji support enabled to +15550123: 'Congratulations! 🎉'", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_sms"], "notes": "SMS with is_unicode flag set to True"},
    {"id": "notifications_t1_011", "text": "Send push notification to user_111, set time-to-live to 3600 seconds.", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_push"], "notes": "Push notification with ttl_seconds parameter"},
    {"id": "notifications_t1_012", "text": "Post Slack notification to channel #general as 'Release Bot' with rocket icon emoji.", "type": 1, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_slack_message"], "notes": "Slack message with username and icon_emoji overrides"},
    {"id": "notifications_t1_013", "text": "Send normal priority push to user_99, title 'Status Update'.", "type": 1, "difficulty": "easy", "domain": "notifications", "expected_tools": ["send_push"], "notes": "Simple push with default priority"},

    # Type 2: Chain
    {"id": "notifications_t2_001", "text": "Send a Slack message about the new user, extract the Slack message TS, and post a thread reply to it.", "type": 2, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_slack_message", "send_slack_message"], "notes": "Send message, retrieve thread timestamp, then send thread reply"},
    {"id": "notifications_t2_002", "text": "Send push notification to customer dev_01, check if they acknowledged, if not send SMS to +12125551122.", "type": 2, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_push", "send_sms"], "notes": "Requires sending push, wait or check state (simulated), then escalate to SMS"},
    {"id": "notifications_t2_003", "text": "Post build result to Slack channel #alerts, and if it failed, send SMS alert to admin phone +15550199.", "type": 2, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_slack_message", "send_sms"], "notes": "Slack post then conditional SMS"},
    {"id": "notifications_t2_004", "text": "Send push warning to user_99, and immediately log a copy of the notification body to Slack #security channel.", "type": 2, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_push", "send_slack_message"], "notes": "Push notification followed by Slack confirmation message"},
    {"id": "notifications_t2_005", "text": "Send confirmation SMS to +447911123456, then send a push confirmation to the user device user_445.", "type": 2, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_sms", "send_push"], "notes": "SMS then push notification chain"},
    {"id": "notifications_t2_006", "text": "Post deployment announcement to Slack #announcements, extract thread_ts, and post confirmation message to the same thread.", "type": 2, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_slack_message", "send_slack_message"], "notes": "Thread creation and follow-up inside Slack"},
    {"id": "notifications_t2_007", "text": "Send push with title 'Auth Code' to user_abc, then send the auth code SMS to +15550011.", "type": 2, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_push", "send_sms"], "notes": "Push alert then SMS token delivery"},
    {"id": "notifications_t2_008", "text": "Post Slack warning about server high load, and send SMS to on-call engineer at +18885550199.", "type": 2, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_slack_message", "send_sms"], "notes": "Escalation warning to Slack and SMS"},
    {"id": "notifications_t2_009", "text": "Send scheduled SMS birthday greeting, and post a log entry to Slack #logging channel.", "type": 2, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_sms", "send_slack_message"], "notes": "SMS scheduling with Slack log trace"},
    {"id": "notifications_t2_010", "text": "Send push reminder to client_1, and if push fails, send SMS to +12125550011.", "type": 2, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_push", "send_sms"], "notes": "Failover push to SMS chain"},
    {"id": "notifications_t2_011", "text": "Send push notification with high priority, then log the transaction ID to Slack channel #billing-logs.", "type": 2, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_push", "send_slack_message"], "notes": "Push notification followed by Slack log posting"},
    {"id": "notifications_t2_012", "text": "Send verification SMS to +18885550122, and when sent, push confirmation user_101.", "type": 2, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_sms", "send_push"], "notes": "Verification flow SMS to Push"},

    # Type 3: Ambiguous
    {"id": "notifications_t3_001", "text": "Send push notification.", "type": 3, "difficulty": "easy", "domain": "notifications", "expected_tools": [], "notes": "Missing 'user_id', 'title', and 'body' parameters."},
    {"id": "notifications_t3_002", "text": "Text my phone number.", "type": 3, "difficulty": "easy", "domain": "notifications", "expected_tools": [], "notes": "Missing 'to' phone number and 'message' content."},
    {"id": "notifications_t3_003", "text": "Post this update to Slack.", "type": 3, "difficulty": "easy", "domain": "notifications", "expected_tools": [], "notes": "Missing 'channel' and message 'text' parameters."},
    {"id": "notifications_t3_004", "text": "Notify user_101.", "type": 3, "difficulty": "easy", "domain": "notifications", "expected_tools": [], "notes": "Missing channel type (SMS? Push? Slack?) and message content."},
    {"id": "notifications_t3_005", "text": "Send message 'Your table is ready' to John.", "type": 3, "difficulty": "medium", "domain": "notifications", "expected_tools": [], "notes": "Missing phone number for SMS or user_id for Push."},
    {"id": "notifications_t3_006", "text": "Post to #general.", "type": 3, "difficulty": "easy", "domain": "notifications", "expected_tools": [], "notes": "Missing message text content."},
    {"id": "notifications_t3_007", "text": "Push an alert: 'System Update'.", "type": 3, "difficulty": "medium", "domain": "notifications", "expected_tools": [], "notes": "Missing user_id parameter for push notification."},
    {"id": "notifications_t3_008", "text": "Send a SMS message to +12125550011.", "type": 3, "difficulty": "easy", "domain": "notifications", "expected_tools": [], "notes": "Missing 'message' content parameter."},
    {"id": "notifications_t3_009", "text": "Schedule SMS to +18885550199.", "type": 3, "difficulty": "medium", "domain": "notifications", "expected_tools": [], "notes": "Missing 'message' body and scheduled time parameters."},
    {"id": "notifications_t3_010", "text": "Slack my team about the meeting.", "type": 3, "difficulty": "medium", "domain": "notifications", "expected_tools": [], "notes": "Missing channel name and message text content."},
    {"id": "notifications_t3_011", "text": "Push details to user device.", "type": 3, "difficulty": "medium", "domain": "notifications", "expected_tools": [], "notes": "Missing user_id and title/body parameters."},
    {"id": "notifications_t3_012", "text": "Send a Slack attachment.", "type": 3, "difficulty": "hard", "domain": "notifications", "expected_tools": [], "notes": "Missing channel and attachment details."},
    {"id": "notifications_t3_013", "text": "Send critical warning push notification.", "type": 3, "difficulty": "medium", "domain": "notifications", "expected_tools": [], "notes": "Missing user_id and body text."},

    # Type 4: Parallel
    {"id": "notifications_t4_001", "text": "Send push notifications to user_1 and user_2 with the same alert.", "type": 4, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_push", "send_push"], "notes": "Two parallel push notifications"},
    {"id": "notifications_t4_002", "text": "Send verification SMS to +15550011 and +15550022 simultaneously.", "type": 4, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_sms", "send_sms"], "notes": "Two parallel SMS messages"},
    {"id": "notifications_t4_003", "text": "Post update to Slack channel #engineering and Slack channel #management in parallel.", "type": 4, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_slack_message", "send_slack_message"], "notes": "Two parallel Slack messages"},
    {"id": "notifications_t4_004", "text": "Send push alert to user_101 and SMS alert to +18885550111 at the same time.", "type": 4, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_push", "send_sms"], "notes": "Push and SMS alerts in parallel"},
    {"id": "notifications_t4_005", "text": "Post build logs to Slack #builds and send push notification to user_admin.", "type": 4, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_slack_message", "send_push"], "notes": "Slack message and Push notification in parallel"},
    {"id": "notifications_t4_006", "text": "Send SMS to developer at +15550199 and post alerts in Slack #alerts simultaneously.", "type": 4, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_sms", "send_slack_message"], "notes": "SMS and Slack message in parallel"},
    {"id": "notifications_t4_007", "text": "Send push to user_a, SMS to +12125550011, and post to Slack #general simultaneously.", "type": 4, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_push", "send_sms", "send_slack_message"], "notes": "Three parallel tools across SMS, Push, Slack"},
    {"id": "notifications_t4_008", "text": "Send alert push notifications to three admins: admin_1, admin_2, and admin_3 in parallel.", "type": 4, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_push", "send_push", "send_push"], "notes": "Three parallel push notifications"},
    {"id": "notifications_t4_009", "text": "Send verification codes to three users via SMS in parallel: +15550011, +15550022, +15550033.", "type": 4, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_sms", "send_sms", "send_sms"], "notes": "Three parallel SMS messages"},
    {"id": "notifications_t4_010", "text": "Post meeting notes to #team-a, #team-b, and #team-c Slack channels simultaneously.", "type": 4, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_slack_message", "send_slack_message", "send_slack_message"], "notes": "Three parallel Slack messages"},
    {"id": "notifications_t4_011", "text": "Send push to user_1 and Slack message to #general in parallel.", "type": 4, "difficulty": "medium", "domain": "notifications", "expected_tools": ["send_push", "send_slack_message"], "notes": "Push and Slack message in parallel"},
    {"id": "notifications_t4_012", "text": "Send SMS to +18885550011 and push alert to user_99 at the same time.", "type": 4, "difficulty": "hard", "domain": "notifications", "expected_tools": ["send_sms", "send_push"], "notes": "SMS and Push alert in parallel"}
]
save_instructions("notifications", notifications_instructions)

# ── 4. Maps Instructions ──
maps_instructions = [
    # Type 1: Single
    {"id": "maps_t1_001", "text": "Get driving directions from Penn Station to Central Park.", "type": 1, "difficulty": "easy", "domain": "maps", "expected_tools": ["get_directions"], "notes": "Simple driving directions request"},
    {"id": "maps_t1_002", "text": "Find nearby restaurants within 2000 meters of Times Square, NYC.", "type": 1, "difficulty": "easy", "domain": "maps", "expected_tools": ["find_nearby"], "notes": "Nearby search with radius and location"},
    {"id": "maps_t1_003", "text": "Calculate distance from Penn Station to Grand Central Terminal using transit mode.", "type": 1, "difficulty": "easy", "domain": "maps", "expected_tools": ["calculate_distance"], "notes": "Distance calculation with transit mode"},
    {"id": "maps_t1_004", "text": "Get walking directions from Times Square to Empire State Building, avoiding tolls.", "type": 1, "difficulty": "medium", "domain": "maps", "expected_tools": ["get_directions"], "notes": "Walking directions with avoid parameter"},
    {"id": "maps_t1_005", "text": "Find coffee shops currently open within 500 meters of my location coordinates 40.7128,-74.0060.", "type": 1, "difficulty": "medium", "domain": "maps", "expected_tools": ["find_nearby"], "notes": "Nearby search with coordinates, cafe place_type, and open_now filter"},
    {"id": "maps_t1_006", "text": "Calculate travel times from Pennsylvania Station to JFK Airport, LaGuardia Airport, and Newark Airport.", "type": 1, "difficulty": "medium", "domain": "maps", "expected_tools": ["calculate_distance"], "notes": "Multi-destination distance calculation"},
    {"id": "maps_t1_007", "text": "Get cycling route directions from Brooklyn Bridge to Dumbo, using imperial units.", "type": 1, "difficulty": "medium", "domain": "maps", "expected_tools": ["get_directions"], "notes": "Cycling directions with units set to imperial"},
    {"id": "maps_t1_008", "text": "Find parking garages with minimum rating of 4 stars within 1000 meters of coordinates 34.0522,-118.2437.", "type": 1, "difficulty": "medium", "domain": "maps", "expected_tools": ["find_nearby"], "notes": "Nearby parking search with rating filter"},
    {"id": "maps_t1_009", "text": "Calculate driving distance between Los Angeles Penn Station and Las Vegas Penn Station.", "type": 1, "difficulty": "medium", "domain": "maps", "expected_tools": ["calculate_distance"], "notes": "Distance between two cities"},
    {"id": "maps_t1_010", "text": "Get transit directions from Boston Common to Harvard Yard departing tomorrow morning at 8:00 AM.", "type": 1, "difficulty": "hard", "domain": "maps", "expected_tools": ["get_directions"], "notes": "Transit directions with departure_time"},
    {"id": "maps_t1_011", "text": "Find nearby pharmacies within 5000 meters of Chicago Downtown.", "type": 1, "difficulty": "easy", "domain": "maps", "expected_tools": ["find_nearby"], "notes": "Pharmacy search"},
    {"id": "maps_t1_012", "text": "Get driving directions from Seattle Penn Station to Portland Penn Station, including waypoint Tacoma Penn Station.", "type": 1, "difficulty": "hard", "domain": "maps", "expected_tools": ["get_directions"], "notes": "Driving directions with waypoints"},
    {"id": "maps_t1_013", "text": "Calculate walking distance from hotel to restaurant.", "type": 1, "difficulty": "easy", "domain": "maps", "expected_tools": ["calculate_distance"], "notes": "Simple walk distance"},

    # Type 2: Chain
    {"id": "maps_t2_001", "text": "Find cafes within 1000 meters of Penn Station, then get driving directions to the highest rated one.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "get_directions"], "notes": "Find cafes, select target address, get directions"},
    {"id": "maps_t2_002", "text": "Search for nearby parking garages near Empire State Building, and then calculate distance from Penn Station to the first parking garage found.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "calculate_distance"], "notes": "Find parking, extract address, calculate distance from Penn Station"},
    {"id": "maps_t2_003", "text": "Find restaurants near Times Square, filter for rating >= 4.5, then get walking directions to the closest one.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "get_directions"], "notes": "Search, select candidate, get walking directions"},
    {"id": "maps_t2_004", "text": "Locate nearby hospitals within 5000 meters of Brooklyn, select the first result, and get driving directions from Penn Station to that hospital.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "get_directions"], "notes": "Search hospitals, extract coordinates, route directions"},
    {"id": "maps_t2_005", "text": "Find cafes near my coordinates 40.7128,-74.0060, then calculate walking distance from Times Square to the cafe found.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "calculate_distance"], "notes": "Search cafe, calculate distance from another location"},
    {"id": "maps_t2_006", "text": "Search for nearby supermarkets near Seattle Penn Station, pick one, and get driving directions from Portland Penn Station to it.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "get_directions"], "notes": "Find supermarket, get directions from distant city"},
    {"id": "maps_t2_007", "text": "Find cafes within 500 meters of Harvard Yard, get the address, and get cycling directions from Boston Common to it.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "get_directions"], "notes": "Search cafe, get cycling directions"},
    {"id": "maps_t2_008", "text": "Find nearby parking near Penn Station, then calculate driving distance from Grand Central Terminal to that parking.", "type": 2, "difficulty": "medium", "domain": "maps", "expected_tools": ["find_nearby", "calculate_distance"], "notes": "Search parking, calculate distance"},
    {"id": "maps_t2_009", "text": "Find restaurants near Seattle Downtown, get directions from Seattle Airport to it, and output the directions.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "get_directions"], "notes": "Find restaurant, get directions"},
    {"id": "maps_t2_010", "text": "Locate gas stations near Times Square, select the first open one, and calculate distance from Penn Station to it.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "calculate_distance"], "notes": "Search open gas station, calculate distance"},
    {"id": "maps_t2_011", "text": "Find pharmacies near coordinates 34.0522,-118.2437, select the nearest one, and get walking directions to it.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "get_directions"], "notes": "Search pharmacy, get walking directions"},
    {"id": "maps_t2_012", "text": "Find hotels near Brooklyn Bridge, pick one, and calculate distance from JFK Airport to it.", "type": 2, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "calculate_distance"], "notes": "Search hotel, calculate distance"},

    # Type 3: Ambiguous
    {"id": "maps_t3_001", "text": "Get directions.", "type": 3, "difficulty": "easy", "domain": "maps", "expected_tools": [], "notes": "Missing both 'origin' and 'destination' parameters."},
    {"id": "maps_t3_002", "text": "Find nearby places.", "type": 3, "difficulty": "easy", "domain": "maps", "expected_tools": [], "notes": "Missing 'location' and 'place_type' parameters."},
    {"id": "maps_t3_003", "text": "Calculate distance.", "type": 3, "difficulty": "easy", "domain": "maps", "expected_tools": [], "notes": "Missing 'origins' and 'destinations' list parameters."},
    {"id": "maps_t3_004", "text": "How do I get to Penn Station?", "type": 3, "difficulty": "easy", "domain": "maps", "expected_tools": [], "notes": "Missing 'origin' parameter (user starting location)."},
    {"id": "maps_t3_005", "text": "Find a restaurant near me.", "type": 3, "difficulty": "medium", "domain": "maps", "expected_tools": [], "notes": "Missing current 'location' parameter coordinates/address."},
    {"id": "maps_t3_006", "text": "Get directions from Times Square.", "type": 3, "difficulty": "easy", "domain": "maps", "expected_tools": [], "notes": "Missing 'destination' parameter."},
    {"id": "maps_t3_007", "text": "Find nearby cafes within a radius.", "type": 3, "difficulty": "medium", "domain": "maps", "expected_tools": [], "notes": "Missing 'location' parameter and explicit 'radius_meters' value."},
    {"id": "maps_t3_008", "text": "Calculate travel time to Seattle Penn Station.", "type": 3, "difficulty": "medium", "domain": "maps", "expected_tools": [], "notes": "Missing 'origins' list parameter."},
    {"id": "maps_t3_009", "text": "Get route avoiding tolls.", "type": 3, "difficulty": "medium", "domain": "maps", "expected_tools": [], "notes": "Missing 'origin' and 'destination' parameters."},
    {"id": "maps_t3_010", "text": "Find gas stations open now.", "type": 3, "difficulty": "medium", "domain": "maps", "expected_tools": [], "notes": "Missing center 'location' parameter."},
    {"id": "maps_t3_011", "text": "Calculate distance in miles.", "type": 3, "difficulty": "medium", "domain": "maps", "expected_tools": [], "notes": "Missing origins and destinations parameters."},
    {"id": "maps_t3_012", "text": "Get directions departing at 8 AM.", "type": 3, "difficulty": "medium", "domain": "maps", "expected_tools": [], "notes": "Missing origin and destination parameters."},
    {"id": "maps_t3_013", "text": "Find nearby hospitals.", "type": 3, "difficulty": "easy", "domain": "maps", "expected_tools": [], "notes": "Missing 'location' parameter."},

    # Type 4: Parallel
    {"id": "maps_t4_001", "text": "Get driving directions from Penn Station to Central Park, and transit directions from Penn Station to Grand Central Terminal.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["get_directions", "get_directions"], "notes": "Two parallel get_directions calls with different routes and modes"},
    {"id": "maps_t4_002", "text": "Find cafes near Penn Station and supermarkets near Times Square simultaneously.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "find_nearby"], "notes": "Two parallel find_nearby calls in different locations"},
    {"id": "maps_t4_003", "text": "Calculate driving distance from Penn Station to JFK Airport, and cycling distance from Penn Station to LaGuardia Airport in parallel.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["calculate_distance", "calculate_distance"], "notes": "Two parallel distance calculations"},
    {"id": "maps_t4_004", "text": "Get walking route Penn Station -> Times Square, and find nearby parking near Times Square.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["get_directions", "find_nearby"], "notes": "Parallel route directions and nearby search"},
    {"id": "maps_t4_005", "text": "Calculate distance from Penn Station to Broadway, and search for restaurants near Broadway at the same time.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["calculate_distance", "find_nearby"], "notes": "Distance calculation and nearby search in parallel"},
    {"id": "maps_t4_006", "text": "Get driving directions NYC -> Boston, and get transit directions Boston -> Harvard yard in parallel.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["get_directions", "get_directions"], "notes": "Parallel directions calls"},
    {"id": "maps_t4_007", "text": "Find ATMs near Times Square, cafes near Penn Station, and parking near Grand Central Terminal simultaneously.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "find_nearby", "find_nearby"], "notes": "Three parallel find_nearby searches"},
    {"id": "maps_t4_008", "text": "Calculate walking distance from Hotel A -> Restaurant, Hotel B -> Cafe, and Hotel C -> Gym in parallel.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["calculate_distance", "calculate_distance", "calculate_distance"], "notes": "Three parallel calculate_distance calls"},
    {"id": "maps_t4_009", "text": "Get route Seattle -> Portland, and get route Portland -> Eugene in parallel.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["get_directions", "get_directions"], "notes": "Parallel routes"},
    {"id": "maps_t4_010", "text": "Find nearby pharmacies near hotel coordinates 40.7128,-74.0060 and coordinates 34.0522,-118.2437 in parallel.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "find_nearby"], "notes": "Parallel nearby searches"},
    {"id": "maps_t4_011", "text": "Calculate driving time Penn Station -> Empire State, and get walking route Penn Station -> Times Square in parallel.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["calculate_distance", "get_directions"], "notes": "Distance and directions parallel calls"},
    {"id": "maps_t4_012", "text": "Find cafes near Seattle Penn Station and calculate distance Seattle Penn Station -> Bellevue in parallel.", "type": 4, "difficulty": "hard", "domain": "maps", "expected_tools": ["find_nearby", "calculate_distance"], "notes": "Find nearby and calculate distance in parallel"}
]
save_instructions("maps", maps_instructions)

# ── 5. Tasks Instructions ──
tasks_instructions = [
    # Type 1: Single
    {"id": "tasks_t1_001", "text": "Create a new task titled 'Fix login bug' with critical priority.", "type": 1, "difficulty": "easy", "domain": "tasks", "expected_tools": ["create_task"], "notes": "Simple task creation"},
    {"id": "tasks_t1_002", "text": "Assign task task_9988 to usr_8877 and notify them.", "type": 1, "difficulty": "easy", "domain": "tasks", "expected_tools": ["assign_task"], "notes": "Assign task specifying assignee and notify flag"},
    {"id": "tasks_t1_003", "text": "Update the status of task task_101 to 'done' with the comment 'PR merged'.", "type": 1, "difficulty": "easy", "domain": "tasks", "expected_tools": ["update_status"], "notes": "Update status with comment"},
    {"id": "tasks_t1_004", "text": "Get all overdue tasks for project proj_backend.", "type": 1, "difficulty": "easy", "domain": "tasks", "expected_tools": ["get_overdue"], "notes": "Get overdue tasks by project filter"},
    {"id": "tasks_t1_005", "text": "Create task 'Submit Q3 reports' due on 2024-09-30 under project proj_finance with high priority.", "type": 1, "difficulty": "medium", "domain": "tasks", "expected_tools": ["create_task"], "notes": "Create task with due date, project, and priority"},
    {"id": "tasks_t1_006", "text": "Assign task task_01 to engineer usr_abc, set due date to 2024-10-15 and send message 'Please review.'", "type": 1, "difficulty": "medium", "domain": "tasks", "expected_tools": ["assign_task"], "notes": "Assign with message and due date"},
    {"id": "tasks_t1_007", "text": "Update task status to 'in_progress' and set completion percentage to 50.", "type": 1, "difficulty": "medium", "domain": "tasks", "expected_tools": ["update_status"], "notes": "Update status with fields payload"},
    {"id": "tasks_t1_008", "text": "Get tasks overdue by at least 7 days for assignee usr_admin, sorted by priority.", "type": 1, "difficulty": "medium", "domain": "tasks", "expected_tools": ["get_overdue"], "notes": "Get overdue with days filter, sorted"},
    {"id": "tasks_t1_009", "text": "Create a subtask titled 'Write unit tests' with parent task task_logins.", "type": 1, "difficulty": "medium", "domain": "tasks", "expected_tools": ["create_task"], "notes": "Create task with parent_task_id"},
    {"id": "tasks_t1_010", "text": "Update task task_404 status to 'blocked' with the comment 'Waiting for API access.'", "type": 1, "difficulty": "easy", "domain": "tasks", "expected_tools": ["update_status"], "notes": "Update status to blocked"},
    {"id": "tasks_t1_011", "text": "Assign task task_1122 to manager usr_boss, do not notify.", "type": 1, "difficulty": "medium", "domain": "tasks", "expected_tools": ["assign_task"], "notes": "Assign task with notify set to False"},
    {"id": "tasks_t1_012", "text": "Get overdue tasks including completed items with a limit of 50, sorted by created date.", "type": 1, "difficulty": "hard", "domain": "tasks", "expected_tools": ["get_overdue"], "notes": "Overdue search with limits and sorting"},
    {"id": "tasks_t1_013", "text": "Create task 'Plan sprint' with tags ['planning', 'sprint5'].", "type": 1, "difficulty": "easy", "domain": "tasks", "expected_tools": ["create_task"], "notes": "Create task with tags"},

    # Type 2: Chain
    {"id": "tasks_t2_001", "text": "Create a task 'Deploy staging', extract the task ID, and assign it to usr_ops.", "type": 2, "difficulty": "medium", "domain": "tasks", "expected_tools": ["create_task", "assign_task"], "notes": "Create task, get ID, assign"},
    {"id": "tasks_t2_002", "text": "Find overdue tasks for project proj_api, get the first task ID, and update its status to 'in_progress'.", "type": 2, "difficulty": "hard", "domain": "tasks", "expected_tools": ["get_overdue", "update_status"], "notes": "Get overdue tasks, get task ID, update status"},
    {"id": "tasks_t2_003", "text": "Create task 'Audit billing logs', assign it to usr_auditor, then update its status to 'todo' with confirmation comment.", "type": 2, "difficulty": "hard", "domain": "tasks", "expected_tools": ["create_task", "assign_task", "update_status"], "notes": "Create, assign, update status chain"},
    {"id": "tasks_t2_004", "text": "Get overdue tasks for usr_dev, check task task_556, and if overdue, update its status to 'blocked'.", "type": 2, "difficulty": "hard", "domain": "tasks", "expected_tools": ["get_overdue", "update_status"], "notes": "Check overdue, update target status"},
    {"id": "tasks_t2_005", "text": "Create task 'Review security alerts', assign to usr_secopps, and set status to 'review'.", "type": 2, "difficulty": "hard", "domain": "tasks", "expected_tools": ["create_task", "assign_task", "update_status"], "notes": "Create, assign, update status"},
    {"id": "tasks_t2_006", "text": "Look up overdue tasks for project proj_db, get the oldest one, and reassign it to usr_dba.", "type": 2, "difficulty": "hard", "domain": "tasks", "expected_tools": ["get_overdue", "assign_task"], "notes": "Get overdue, assign task"},
    {"id": "tasks_t2_007", "text": "Create a sprint planning task, get its ID, then assign it to usr_scrummaster with a due date.", "type": 2, "difficulty": "medium", "domain": "tasks", "expected_tools": ["create_task", "assign_task"], "notes": "Create task, assign task"},
    {"id": "tasks_t2_008", "text": "Get overdue tasks, pick the first one, assign it to usr_support, and set status to 'in_progress'.", "type": 2, "difficulty": "hard", "domain": "tasks", "expected_tools": ["get_overdue", "assign_task", "update_status"], "notes": "Get overdue, assign, update status"},
    {"id": "tasks_t2_009", "text": "Create subtask 'Write readme', get parent task task_docs, assign it to usr_writer.", "type": 2, "difficulty": "medium", "domain": "tasks", "expected_tools": ["create_task", "assign_task"], "notes": "Create subtask, assign"},
    {"id": "tasks_t2_010", "text": "Look up overdue items, find the one for usr_designer, and mark its status as 'done'.", "type": 2, "difficulty": "hard", "domain": "tasks", "expected_tools": ["get_overdue", "update_status"], "notes": "Get overdue, update target done"},
    {"id": "tasks_t2_011", "text": "Create task 'Fix layout', assign to usr_ui, and log comment 'Urgent feedback.'", "type": 2, "difficulty": "hard", "domain": "tasks", "expected_tools": ["create_task", "assign_task", "update_status"], "notes": "Create, assign, update status"},
    {"id": "tasks_t2_012", "text": "Get overdue tasks for usr_qa, pick task task_tests, and assign it to usr_testlead.", "type": 2, "difficulty": "medium", "domain": "tasks", "expected_tools": ["get_overdue", "assign_task"], "notes": "Get overdue, assign task"},

    # Type 3: Ambiguous
    {"id": "tasks_t3_001", "text": "Create a task.", "type": 3, "difficulty": "easy", "domain": "tasks", "expected_tools": [], "notes": "Missing 'title' parameter. Must ask for clarification."},
    {"id": "tasks_t3_002", "text": "Assign the task.", "type": 3, "difficulty": "easy", "domain": "tasks", "expected_tools": [], "notes": "Missing 'task_id' and 'assignee_id' parameters."},
    {"id": "tasks_t3_003", "text": "Update task status.", "type": 3, "difficulty": "easy", "domain": "tasks", "expected_tools": [], "notes": "Missing 'task_id' and 'status' parameters."},
    {"id": "tasks_t3_004", "text": "Check overdue.", "type": 3, "difficulty": "easy", "domain": "tasks", "expected_tools": [], "notes": "Vague command, missing filter parameters (project_id or assignee_id)."},
    {"id": "tasks_t3_005", "text": "Create sprint task for John.", "type": 3, "difficulty": "medium", "domain": "tasks", "expected_tools": [], "notes": "Missing task title and assignee_id. Clarify task name and ID."},
    {"id": "tasks_t3_006", "text": "Assign task_999.", "type": 3, "difficulty": "easy", "domain": "tasks", "expected_tools": [], "notes": "Missing 'assignee_id' parameter."},
    {"id": "tasks_t3_007", "text": "Update status to done.", "type": 3, "difficulty": "easy", "domain": "tasks", "expected_tools": [], "notes": "Missing 'task_id' parameter."},
    {"id": "tasks_t3_008", "text": "Get overdue tasks for project.", "type": 3, "difficulty": "medium", "domain": "tasks", "expected_tools": [], "notes": "Missing 'project_id' parameter."},
    {"id": "tasks_t3_009", "text": "Create task 'Audit' with tags.", "type": 3, "difficulty": "medium", "domain": "tasks", "expected_tools": [], "notes": "Vague tags list. Missing tags value."},
    {"id": "tasks_t3_010", "text": "Update task task_101.", "type": 3, "difficulty": "easy", "domain": "tasks", "expected_tools": [], "notes": "Missing 'status' parameter to update to."},
    {"id": "tasks_t3_011", "text": "Assign task to usr_dev.", "type": 3, "difficulty": "easy", "domain": "tasks", "expected_tools": [], "notes": "Missing 'task_id' parameter."},
    {"id": "tasks_t3_012", "text": "Get overdue tasks past deadline.", "type": 3, "difficulty": "medium", "domain": "tasks", "expected_tools": [], "notes": "Missing project/assignee filters."},
    {"id": "tasks_t3_013", "text": "Create subtask.", "type": 3, "difficulty": "medium", "domain": "tasks", "expected_tools": [], "notes": "Missing title and parent_task_id."},

    # Type 4: Parallel
    {"id": "tasks_t4_001", "text": "Create task 'Task A' and create task 'Task B' in parallel.", "type": 4, "difficulty": "easy", "domain": "tasks", "expected_tools": ["create_task", "create_task"], "notes": "Two parallel create_task calls"},
    {"id": "tasks_t4_002", "text": "Assign task task_1 to usr_1 and assign task task_2 to usr_2 simultaneously.", "type": 4, "difficulty": "medium", "domain": "tasks", "expected_tools": ["assign_task", "assign_task"], "notes": "Two parallel assign_task calls"},
    {"id": "tasks_t4_003", "text": "Update status of task task_1 to 'done' and task task_2 to 'blocked' at the same time.", "type": 4, "difficulty": "medium", "domain": "tasks", "expected_tools": ["update_status", "update_status"], "notes": "Two parallel update_status calls"},
    {"id": "tasks_t4_004", "text": "Get overdue tasks for usr_1 and get overdue tasks for usr_2 in parallel.", "type": 4, "difficulty": "easy", "domain": "tasks", "expected_tools": ["get_overdue", "get_overdue"], "notes": "Two parallel get_overdue calls"},
    {"id": "tasks_t4_005", "text": "Create task 'Deploy staging' and assign task task_prep to usr_dev at the same time.", "type": 4, "difficulty": "hard", "domain": "tasks", "expected_tools": ["create_task", "assign_task"], "notes": "Create task and assign task in parallel"},
    {"id": "tasks_t4_006", "text": "Update task task_101 status to 'done' and get overdue tasks for project proj_db in parallel.", "type": 4, "difficulty": "hard", "domain": "tasks", "expected_tools": ["update_status", "get_overdue"], "notes": "Update status and get overdue in parallel"},
    {"id": "tasks_t4_007", "text": "Create task 'Release v1.0', assign task_verify to usr_qa, and update task_pr status to 'done' in parallel.", "type": 4, "difficulty": "hard", "domain": "tasks", "expected_tools": ["create_task", "assign_task", "update_status"], "notes": "Three parallel tools in tasks domain"},
    {"id": "tasks_t4_008", "text": "Assign tasks: task_a to usr_1, task_b to usr_2, and task_c to usr_3 in parallel.", "type": 4, "difficulty": "hard", "domain": "tasks", "expected_tools": ["assign_task", "assign_task", "assign_task"], "notes": "Three parallel assignments"},
    {"id": "tasks_t4_009", "text": "Create tasks 'Refactor code', 'Fix CSS', and 'Write docs' in parallel.", "type": 4, "difficulty": "hard", "domain": "tasks", "expected_tools": ["create_task", "create_task", "create_task"], "notes": "Three parallel creations"},
    {"id": "tasks_t4_010", "text": "Update status of task_1, task_2, and task_3 to 'review' simultaneously.", "type": 4, "difficulty": "hard", "domain": "tasks", "expected_tools": ["update_status", "update_status", "update_status"], "notes": "Three parallel updates"},
    {"id": "tasks_t4_011", "text": "Create task 'Review PR' and get overdue tasks for project proj_api in parallel.", "type": 4, "difficulty": "medium", "domain": "tasks", "expected_tools": ["create_task", "get_overdue"], "notes": "Create task and get overdue in parallel"},
    {"id": "tasks_t4_012", "text": "Assign task task_55 to usr_ops and update status of task task_22 to 'in_progress' simultaneously.", "type": 4, "difficulty": "hard", "domain": "tasks", "expected_tools": ["assign_task", "update_status"], "notes": "Assign task and update status in parallel"}
]
save_instructions("tasks", tasks_instructions)

# ── 6. Database Instructions ──
database_instructions = [
    # Type 1: Single
    {"id": "database_t1_001", "text": "Query all records from table 'users' where status is 'active'.", "type": 1, "difficulty": "easy", "domain": "database", "expected_tools": ["query_records"], "notes": "Query records with simple filters"},
    {"id": "database_t1_002", "text": "Insert a new record into table 'contacts' with data {'name': 'John', 'email': 'john@test.com'}.", "type": 1, "difficulty": "easy", "domain": "database", "expected_tools": ["insert_record"], "notes": "Insert record into table"},
    {"id": "database_t1_003", "text": "Update records in table 'orders' matching {'id': 101} with updates {'status': 'shipped'}.", "type": 1, "difficulty": "easy", "domain": "database", "expected_tools": ["update_record"], "notes": "Update record matching filter"},
    {"id": "database_t1_004", "text": "Delete records from table 'sessions' matching {'expired': true}.", "type": 1, "difficulty": "easy", "domain": "database", "expected_tools": ["delete_record"], "notes": "Delete record matching filter"},
    {"id": "database_t1_005", "text": "Query table 'transactions' for columns ['id', 'amount'] where amount > 100 with limit 50, ordered by date desc.", "type": 1, "difficulty": "medium", "domain": "database", "expected_tools": ["query_records"], "notes": "Query with fields, limit, and sorting"},
    {"id": "database_t1_006", "text": "Insert record into table 'logs', ignoring conflicts if unique key exists.", "type": 1, "difficulty": "medium", "domain": "database", "expected_tools": ["insert_record"], "notes": "Insert with on_conflict ignore flag"},
    {"id": "database_t1_007", "text": "Update table 'users', setting status to 'suspended' for rows matching {'inactive': true}, return the updated records.", "type": 1, "difficulty": "medium", "domain": "database", "expected_tools": ["update_record"], "notes": "Update record returning updated rows"},
    {"id": "database_t1_008", "text": "Perform soft delete on table 'employees' matching filter {'id': 45}.", "type": 1, "difficulty": "medium", "domain": "database", "expected_tools": ["delete_record"], "notes": "Delete with soft_delete set to True"},
    {"id": "database_t1_009", "text": "Query table 'products' with offset 100 and limit 25.", "type": 1, "difficulty": "medium", "domain": "database", "expected_tools": ["query_records"], "notes": "Query with pagination parameters"},
    {"id": "database_t1_010", "text": "Insert data {'title': 'Hello'} into table 'articles' and return the generated ID.", "type": 1, "difficulty": "easy", "domain": "database", "expected_tools": ["insert_record"], "notes": "Insert with return_id True"},
    {"id": "database_t1_011", "text": "Update database table 'settings' for key 'theme' to value 'dark'.", "type": 1, "difficulty": "easy", "domain": "database", "expected_tools": ["update_record"], "notes": "Simple update"},
    {"id": "database_t1_012", "text": "Delete rows from table 'temporary_cache' matching {'created_before': '2024-01-01'} returning deleted rows.", "type": 1, "difficulty": "hard", "domain": "database", "expected_tools": ["delete_record"], "notes": "Delete returning deleted rows"},
    {"id": "database_t1_013", "text": "Query database table 'feedback' ordering results by rating ascending.", "type": 1, "difficulty": "medium", "domain": "database", "expected_tools": ["query_records"], "notes": "Query with sorting direction asc"},

    # Type 2: Chain
    {"id": "database_t2_001", "text": "Insert user info into table 'users', extract the returned user ID, and query records from 'users' with that ID.", "type": 2, "difficulty": "medium", "domain": "database", "expected_tools": ["insert_record", "query_records"], "notes": "Insert user, get ID, query back"},
    {"id": "database_t2_002", "text": "Query records from table 'orders' where status is 'pending', take the first order ID, and update its status to 'processing'.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["query_records", "update_record"], "notes": "Query orders, extract ID, update record status"},
    {"id": "database_t2_003", "text": "Query table 'contacts' for 'Bob', get the contact ID, update his email address, then query the updated record.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["query_records", "update_record", "query_records"], "notes": "Query, update, query back chain"},
    {"id": "database_t2_004", "text": "Insert a logs row into table 'logs', get the log ID, and immediately delete the record to test connection.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["insert_record", "delete_record"], "notes": "Insert log, delete log"},
    {"id": "database_t2_005", "text": "Query table 'settings' for theme key, and if found, update the value to 'light'.", "type": 2, "difficulty": "medium", "domain": "database", "expected_tools": ["query_records", "update_record"], "notes": "Query settings, update value"},
    {"id": "database_t2_006", "text": "Insert test record into table 'debug', update it with status 'verified', then delete it from 'debug' table.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["insert_record", "update_record", "delete_record"], "notes": "Insert, update, delete chain"},
    {"id": "database_t2_007", "text": "Query table 'tickets' where severity is 'high', extract the first ticket ID, and soft delete it.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["query_records", "delete_record"], "notes": "Query ticket, soft delete"},
    {"id": "database_t2_008", "text": "Insert record into table 'transactions', retrieve the generated ID, and update its settlement status to settled.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["insert_record", "update_record"], "notes": "Insert row, update row"},
    {"id": "database_t2_009", "text": "Query table 'users' for email 'admin@local', get the ID, and query all activities for that user in 'logs' table.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["query_records", "query_records"], "notes": "Query user, query logs referencing user ID"},
    {"id": "database_t2_010", "text": "Query table 'orders' for order_id 101, get the total amount, insert a validation log into 'logs' table.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["query_records", "insert_record"], "notes": "Query row, insert validation log"},
    {"id": "database_t2_011", "text": "Insert data into 'sessions', get the session token, update the user's last login date in 'users' table.", "type": 2, "difficulty": "hard", "domain": "database", "expected_tools": ["insert_record", "update_record"], "notes": "Insert session, update user row"},
    {"id": "database_t2_012", "text": "Query records from table 'temp_keys', pick the expired key ID, and delete it from 'temp_keys'.", "type": 2, "difficulty": "medium", "domain": "database", "expected_tools": ["query_records", "delete_record"], "notes": "Query expired key, delete it"},

    # Type 3: Ambiguous
    {"id": "database_t3_001", "text": "Query records from database.", "type": 3, "difficulty": "easy", "domain": "database", "expected_tools": [], "notes": "Missing 'table' parameter. Must ask for clarification."},
    {"id": "database_t3_002", "text": "Insert a new row.", "type": 3, "difficulty": "easy", "domain": "database", "expected_tools": [], "notes": "Missing 'table' and 'data' parameters."},
    {"id": "database_t3_003", "text": "Update database record.", "type": 3, "difficulty": "easy", "domain": "database", "expected_tools": [], "notes": "Missing 'table', 'filters', and 'updates' parameters."},
    {"id": "database_t3_004", "text": "Delete records from database.", "type": 3, "difficulty": "easy", "domain": "database", "expected_tools": [], "notes": "Missing 'table' and 'filters' parameters. Empty filters is rejected for safety."},
    {"id": "database_t3_005", "text": "Add user Bob to database.", "type": 3, "difficulty": "medium", "domain": "database", "expected_tools": [], "notes": "Missing table columns data. Clarify table name and properties."},
    {"id": "database_t3_006", "text": "Query users table.", "type": 3, "difficulty": "medium", "domain": "database", "expected_tools": ["query_records"], "notes": "Vague search query, missing filters parameter. Query all columns with defaults."},
    {"id": "database_t3_007", "text": "Update table 'orders' to shipped.", "type": 3, "difficulty": "easy", "domain": "database", "expected_tools": [], "notes": "Missing 'filters' parameter to select which orders to update."},
    {"id": "database_t3_008", "text": "Delete rows from 'logs' table.", "type": 3, "difficulty": "medium", "domain": "database", "expected_tools": [], "notes": "Missing 'filters' parameter. Empty filters are rejected for safety."},
    {"id": "database_t3_009", "text": "Insert record into table 'settings'.", "type": 3, "difficulty": "easy", "domain": "database", "expected_tools": [], "notes": "Missing 'data' parameter payload."},
    {"id": "database_t3_010", "text": "Update active status.", "type": 3, "difficulty": "medium", "domain": "database", "expected_tools": [], "notes": "Missing table, filters, and updates parameters."},
    {"id": "database_t3_011", "text": "Delete transaction records.", "type": 3, "difficulty": "easy", "domain": "database", "expected_tools": [], "notes": "Missing table name and filters."},
    {"id": "database_t3_012", "text": "Query database table with sorting.", "type": 3, "difficulty": "medium", "domain": "database", "expected_tools": [], "notes": "Missing table parameter."},
    {"id": "database_t3_013", "text": "Insert record with conflict handling.", "type": 3, "difficulty": "medium", "domain": "database", "expected_tools": [], "notes": "Missing table and data payload."},

    # Type 4: Parallel
    {"id": "database_t4_001", "text": "Query all records from table 'users' and query all records from table 'logs' in parallel.", "type": 4, "difficulty": "easy", "domain": "database", "expected_tools": ["query_records", "query_records"], "notes": "Two parallel query_records calls on different tables"},
    {"id": "database_t4_002", "text": "Insert data into 'users' table and insert data into 'profiles' table simultaneously.", "type": 4, "difficulty": "medium", "domain": "database", "expected_tools": ["insert_record", "insert_record"], "notes": "Two parallel insert_record calls"},
    {"id": "database_t4_003", "text": "Update status of order 1 to 'done' and update status of order 2 to 'blocked' in parallel.", "type": 4, "difficulty": "medium", "domain": "database", "expected_tools": ["update_record", "update_record"], "notes": "Two parallel update_record calls"},
    {"id": "database_t4_004", "text": "Delete records from 'sessions' and delete records from 'temp_cache' at the same time.", "type": 4, "difficulty": "hard", "domain": "database", "expected_tools": ["delete_record", "delete_record"], "notes": "Two parallel delete_record calls"},
    {"id": "database_t4_005", "text": "Query records from table 'settings' while inserting a record into 'logs' table in parallel.", "type": 4, "difficulty": "hard", "domain": "database", "expected_tools": ["query_records", "insert_record"], "notes": "Query and insert in parallel"},
    {"id": "database_t4_006", "text": "Update user 1 record in 'users' and query activity log for user 1 in 'logs' simultaneously.", "type": 4, "difficulty": "hard", "domain": "database", "expected_tools": ["update_record", "query_records"], "notes": "Update and query in parallel"},
    {"id": "database_t4_007", "text": "Insert record into 'users', update record in 'contacts', and query table 'logs' in parallel.", "type": 4, "difficulty": "hard", "domain": "database", "expected_tools": ["insert_record", "update_record", "query_records"], "notes": "Three parallel tools in database domain"},
    {"id": "database_t4_008", "text": "Delete logs matching ID 1, delete logs matching ID 2, and delete logs matching ID 3 in parallel.", "type": 4, "difficulty": "hard", "domain": "database", "expected_tools": ["delete_record", "delete_record", "delete_record"], "notes": "Three parallel deletions"},
    {"id": "database_t4_009", "text": "Query 'products' table, query 'orders' table, and query 'inventory' table simultaneously.", "type": 4, "difficulty": "hard", "domain": "database", "expected_tools": ["query_records", "query_records", "query_records"], "notes": "Three parallel queries"},
    {"id": "database_t4_010", "text": "Update settings for 'timezone', update settings for 'language', and update settings for 'theme' in parallel.", "type": 4, "difficulty": "hard", "domain": "database", "expected_tools": ["update_record", "update_record", "update_record"], "notes": "Three parallel updates"},
    {"id": "database_t4_011", "text": "Insert record in 'errors' and query 'system_status' table at the same time.", "type": 4, "difficulty": "medium", "domain": "database", "expected_tools": ["insert_record", "query_records"], "notes": "Insert and query in parallel"},
    {"id": "database_t4_012", "text": "Update record in 'transactions' and delete record from 'temp_keys' simultaneously.", "type": 4, "difficulty": "hard", "domain": "database", "expected_tools": ["update_record", "delete_record"], "notes": "Update and delete in parallel"}
]
save_instructions("database", database_instructions)

print("Finished writing all missing seed instructions!")
