"""
preference.py — Preference Pair Builder for RLHF/DPO.

Compares examples generated by Grok and Gemini for the same instruction.
If both are valid and their score difference is >= 0.05, it builds a
PreferencePair with "chosen" and "rejected" conversation structures.
"""

from __future__ import annotations

import uuid
import json
import logging
from typing import Any, Optional

from src.models import (
    Example,
    ExampleType,
    Generator,
    PreferencePair,
    ScoreResult,
)

logger = logging.getLogger(__name__)

# Minimum score difference to form a preference pair (to filter out noise)
MIN_SCORE_DELTA = 0.05


class PreferencePairBuilder:
    """
    Groups examples by instruction, compares scores, and constructs DPO preference pairs.
    """

    def __init__(self) -> None:
        pass

    def build_pair(
        self,
        instruction_id: str,
        instruction_text: str,
        domain: str,
        example_type: int,
        example_a: Example,
        score_a: ScoreResult,
        example_b: Example,
        score_b: ScoreResult,
    ) -> Optional[PreferencePair]:
        """
        Compares two examples for the same instruction and returns a PreferencePair if eligible.
        """
        # Both examples must be valid
        if not example_a.is_valid or not example_b.is_valid:
            return None

        # Determine chosen vs rejected
        if score_a.composite_score >= score_b.composite_score:
            chosen_ex, chosen_score = example_a, score_a
            rejected_ex, rejected_score = example_b, score_b
        else:
            chosen_ex, chosen_score = example_b, score_b
            rejected_ex, rejected_score = example_a, score_a

        delta = chosen_score.composite_score - rejected_score.composite_score

        # Check threshold
        if delta < MIN_SCORE_DELTA:
            logger.debug(
                f"Skipping preference pair for {instruction_id}: score delta ({delta:.3f}) below threshold ({MIN_SCORE_DELTA})"
            )
            return None

        # Build OpenAI/DPO format conversations
        chosen_conv = self.to_openai_format(chosen_ex.conversation)
        rejected_conv = self.to_openai_format(rejected_ex.conversation)

        # Prompt for DPO is typically the user's message
        # In our taxonomy, the system prompt is system, user is instruction text.
        prompt = instruction_text

        pair = PreferencePair(
            instruction_id=instruction_id,
            instruction_text=instruction_text,
            domain=domain,
            example_type=example_type,
            chosen_example_id=chosen_ex.id,
            rejected_example_id=rejected_ex.id,
            chosen_generator=chosen_ex.generator,
            rejected_generator=rejected_ex.generator,
            chosen_score=chosen_score.composite_score,
            rejected_score=rejected_score.composite_score,
            score_delta=round(delta, 4),
            prompt=prompt,
            chosen={"messages": chosen_conv},
            rejected={"messages": rejected_conv},
        )
        return pair

    @staticmethod
    def to_openai_format(conversation: list[Any]) -> list[dict[str, Any]]:
        """
        Converts internal ConversationTurn list to standard OpenAI Messages format.
        Assigns matching tool_call_id to assistant call and tool response.
        """
        messages = []
        tool_call_ids: dict[str, str] = {}

        for turn in conversation:
            # Map role
            role = turn.role

            if role == "system" or role == "user":
                messages.append({"role": role, "content": turn.content})

            elif role == "assistant":
                msg: dict[str, Any] = {"role": "assistant"}
                if turn.content:
                    msg["content"] = turn.content
                else:
                    msg["content"] = None

                if turn.tool_calls:
                    openai_calls = []
                    for tc in turn.tool_calls:
                        # Generate a consistent ID for this tool call
                        call_id = f"call_{uuid.uuid4().hex[:8]}"
                        # Store name -> ID mapping so we can link the tool result later
                        tool_call_ids[tc.name] = call_id

                        openai_calls.append({
                            "id": call_id,
                            "type": "function",
                            "function": {
                                "name": tc.name,
                                "arguments": json.dumps(tc.arguments),
                            },
                        })
                    msg["tool_calls"] = openai_calls

                messages.append(msg)

            elif role == "tool":
                # Find matching tool_call_id by name
                call_id = tool_call_ids.get(turn.name, f"call_{uuid.uuid4().hex[:8]}")
                messages.append({
                    "role": "tool",
                    "tool_call_id": call_id,
                    "name": turn.name,
                    "content": turn.content,
                })

        return messages
